esphome:
  name: esp-watercounter
  platform: ESP8266
  board: d1_mini
  on_boot:
    - logger.log: "Wait for MQTT connected"
    - wait_until:
        mqtt.connected:
    - delay: 3s
    - if:
        condition:
          mqtt.connected:
        then:
        - globals.set:
            id: water_count_var
            value: !lambda |-
              return id(water_counter).state;

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 172.16.1.120
    subnet: 255.255.255.0
    gateway: 172.16.1.1
    dns1: 172.16.1.1

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: false

globals:
  - id: water_count_var
    type: int
    restore_value: no

time:
  - platform: sntp
    on_time:
      # Every 5 minutes
      - seconds: 0
        minutes: /5
        then:
          - if:
              condition:
                lambda: |-
                  return id(water_count_var) > 0;
              then:
              - mqtt.publish:
                  topic: /pantry/watercounter
                  retain: true
                  payload: !lambda |-
                    return to_string(id(water_count_var));

binary_sensor:
  - platform: gpio
    name: "Pantry Tank cap"
    device_class: window
    pin:
      number: 5
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 150ms
      - delayed_off: 150ms

  - platform: gpio
    name: "Pantry Water usage"
    id: water_usage
    internal: true
    pin:
      number: 4
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      then:
        - if:
            condition:
              lambda: |-
                return id(water_count_var) > 0;
            then:
              - lambda: 'id(water_count_var) += 1;'
# Moved in "time" section to send accumulated values every 5 minutes
#              - mqtt.publish:
#                  topic: /pantry/watercounter
#                  retain: true
#                  payload: !lambda |-
#                    return to_string(id(water_count_var));

sensor:
  - platform: mqtt_subscribe
    name: "Pantry Water count (L)"
    icon: "mdi:water-pump"
    id: water_counter
    accuracy_decimals: 0
    unit_of_measurement: 'L'
    topic: /pantry/watercounter
