- platform: mqtt
  name: 2 Bathroom Occupancy
  state_topic: "2_bathroom/occupancy"
  payload_on: "On"
  payload_off: "Off"
  device_class: occupancy

- platform: template
  sensors:
    bathroom_toilet_usage:
      friendly_name: "Bathroom Toilet usage"
      delay_on:
        seconds: 5
      delay_off:
        seconds: 10
      device_class: occupancy
      value_template: >-
        {{ is_state('binary_sensor.bathroom_toilet_state', 'on') }}
