- platform: template
  sensors:
    bathroom_toilet_usage:
      friendly_name: "Bathroom Toilet usage"
      delay_on:
        seconds: 5
      delay_off:
        seconds: 10
      device_class: occupancy
      value_template: >-
        {{ is_state('binary_sensor.bathroom_toilet_state', 'on') }}
